sudo: false
language: python
python:
  - "2.7"
branches:
  except:
    travis-tested
env:
  global:
    - NIFTY_TRAVIS_CACHE_REPO=https://github.com/nimbis/travis-cache-public.git
install:
  - make reqs
before_script:
  - git clone https://github.com/nimbis/nifty.git ./.nifty
script:
  - source .nifty/nifty-script
  - verify_coverage_improvement
  - test_and_tag
  - make pep8
  - make flake8
after_success:
  - coveralls
